name: Build Equip360 for Windows

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Show files
        run: Get-ChildItem -Recurse -File | Select-Object FullName

      - name: Install dependencies
        run: npm install

      - name: Obfuscate
        run: node obfuscate.js

      - name: Build installer
        run: npx electron-builder --win nsis --x64 --publish never

      - name: Upload the installer
        uses: actions/upload-artifact@v4
        with:
          name: Equip360-Windows
          path: dist/*.exe
